# Generated by Django 4.2.10 on 2024-02-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(1, 'True'), (0, 'False')], default=1),
        ),
        migrations.AlterField(
            model_name='ateendee',
            name='newsletter',
            field=models.IntegerField(choices=[(1, 'True'), (0, 'False')], default=1),
        ),
        migrations.AlterField(
            model_name='memberateendee',
            name='newsletter',
            field=models.IntegerField(choices=[(1, 'True'), (0, 'False')], default=1),
        ),
    ]
