# Generated by Django 4.2.9 on 2024-02-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_status_alter_ateendee_newsletter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ateendee',
            name='newsletter',
            field=models.IntegerField(choices=[(0, 'True'), (1, 'False')], default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(0, 'True'), (1, 'False')], default=1),
        ),
        migrations.AlterField(
            model_name='memberateendee',
            name='newsletter',
            field=models.IntegerField(choices=[(0, 'True'), (1, 'False')], default=0),
        ),
    ]
