# Generated by Django 4.2.9 on 2024-02-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_guest_memberguest_programmes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmes',
            name='status',
            field=models.IntegerField(choices=[(0, 'draft'), (1, 'published')], default=1),
        ),
    ]
