# Generated by Django 4.2.9 on 2024-02-21 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_programmes_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmes',
            options={'ordering': ['-registration_expires']},
        ),
    ]
