# Generated by Django 4.2.9 on 2024-02-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_attendee_remove_memberguest_event_delete_guest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
