# Generated by Django 4.2.9 on 2024-03-03 21:29

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('picture', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('bio', models.TextField(blank=True, max_length=1000, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('where_from', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')])),
                ('relationship_status', models.IntegerField(choices=[(0, 'Choose not to say'), (1, 'Yes'), (2, 'No'), (3, 'Not sure'), (4, 'Married')], default=0)),
                ('favourite_scripture', models.CharField(blank=True, max_length=500, null=True)),
                ('favourite_bible_character', models.CharField(blank=True, max_length=50, null=True)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('handle', models.CharField(blank=True, max_length=50, null=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'inactive'), (1, 'active')], default=1)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_date'],
            },
        ),
    ]
