# Generated by Django 4.2.9 on 2024-02-24 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_profile_delete_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationship_status',
            field=models.IntegerField(choices=[(0, 'Choose not to say'), (1, 'Yes'), (2, 'No'), (3, 'Not sure'), (4, 'Married')], default=0),
        ),
    ]
