# Generated by Django 4.2.10 on 2024-02-15 02:18

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('active_date', models.DateField()),
                ('memory_verse', models.TextField()),
                ('content', models.TextField()),
                ('bible_reading_plan1', models.CharField(blank=True, max_length=30, null=True)),
                ('bible_reading_plan2', models.CharField(blank=True, max_length=30, null=True)),
                ('background_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('title_image', cloudinary.models.CloudinaryField(default='placeholder2', max_length=255, verbose_name='image')),
                ('status', models.IntegerField(choices=[(0, 'draft'), (1, 'published')], default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devotional_posts', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='devotional_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-active_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL)),
                ('likes2', models.ManyToManyField(related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='devotional.post')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
