# Generated by Django 4.2.9 on 2024-02-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotional', '0003_alter_comment_author_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='memory_verse',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
